name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for Frontend
      run: docker build -t anaseg/banking-application-frontend-latest --build-arg VITE_REACT_APP_BACKEND_BASEURL="${{ secrets.VITE_REACT_APP_BACKEND_BASEURL }}" .

    - name: Push Docker Image to Docker Hub
      run: docker push anaseg/banking-application-frontend-latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Docker Hub
        run: docker pull anaseg/banking-application-frontend-latest

      - name: Stop and Remove Existing Frontend Container
        run: |
          docker stop banking-application-frontend-latest || echo "No running frontend container found"
          docker rm banking-application-frontend-latest || echo "No frontend container to remove"

      - name: Run Frontend Docker Container
        run: |
          docker run -d -p 80:80 --name banking-application-frontend-latest \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          anaseg/banking-application-frontend-latest









